# Estimação de Razões e Funções de Totais {#razao}

## Razões populacionais como parâmetros de interesse

Muitas vezes na prática de pesquisas por amostragem, o *parâmetro* populacional de interesse é uma razão entre os totais (ou médias) de duas variáveis de pesquisa definidas para cada unidade da população. Nesse caso, o *parâmetro* é denominado *razão de totais (ou de médias)* ou simplesmente *razão*. Chamando de $y$ e $x$ as variáveis cujos totais aparecem no numerador e denominador da razão, respectivamente, define-se a *razão* $R$ como:

\begin{equation}
R = \frac{\sum_{i\in U}y_i}{\sum_{i\in U}x_i} = \frac{Y}{X}=\frac{\overline{Y}}{\overline{X}} (\#eq:eqraz1)
\end{equation}
 
Alguns exemplos de razões de interesse incluem:

- a razão entre o total dos gastos com transporte e o total da renda das famílias;

- a produtividade da lavoura de certo produto, definida como a razão entre o total da quantidade colhida do produto pelo total da área plantada com esse produto;

- o salário médio dos trabalhadores da indústria, definido como a razão entre o total dos salários dos trabalhadores da indústria e o número total de trabalhadores da indústria; e

- a densidade de pessoas por dormitório em domicílios particulares, definida como a razão entre o número de pessoas residentes em domicílios particulares e o número total de dormitórios em domicílios particulares.

No caso da razão entre o total dos gastos com transporte ($y$) e o total da renda das famílias ($x$), a razão fica definida como:

\begin{equation}
\frac{\textrm {Total dos gastos com transporte}}{\textrm{Total da renda}} = \frac{\sum_{i\in U}y_i}{\sum_{i\in U}x_i}=\frac{Y}{X} = R 
\end{equation}
 
## Razão de médias versus média de razões

Um cuidado importante aqui é compreender o significado do parâmetro de interesse. A razão de totais $R$ não é a média $\left(\overline{R} = \sum_{i\in U}{r_i}/{N} \right)$ das *razões por unidade* $\left(r_i=y_i/x_i\right)$. Neste capítulo estamos interessados na razão de totais (ou médias), e não na média de razões. A média de razões $\left(\overline{R} \right)$ pode ser estimada usando os estimadores habituais de médias populacionais discutidos no capítulo \@ref(visger), aplicados à variável $r$ definida aqui.

**(#exm:exmrazao1)** Considere as densidades de habitantes por área (em $km^2$) das unidades da federação brasileiras apresentadas na Tabela \@ref(tab:tabrazao1), conforme o Censo 2010. Neste exemplo, vemos como uma discrepância grande pode ocorrer entre as duas quantidades (a razão de médias e a médias das razões), quando os valores de $r_i$  são muito dispersos.

```{r, echo=FALSE, label="tabrazao1"}
suppressMessages(library(kableExtra))
knitr::kable(NULL,caption= "Densidade por Unidade da Federação, média das razões e razão das médias para o Brasil") 
```
|Unidade da Federação|Densidade ($\text{Hab}/Km^2$)|
|:-------------------|:-----:|
|Rondônia            |6,6    |
|Acre                |4,5    |
|Amazonas            |2,2    |
|Roraima             |2,0    |
|Pará                |6,1    |
|Amapá               |4,7    |
|Tocantins           |5,0    |
|Maranhão            |19,8   |
|Piauí               |12,4   |
|Ceará               |56,8   |
|Rio Grande do Norte |60,0   |
|Paraíba             |66,7   |
|Pernambuco          |89,6   |
|Alagoas             |112,3  |
|Sergipe             |94,4   |
|Bahia               |24,8   |
|Minas Gerais        |33,4   |
|Espírito Santo      |76,3   |
|Rio de Janeiro      |365,2  |
|São Paulo           |166,3  |
|Paraná              |52,4   |
|Santa Catarina      |65,3   |
|Rio Grande do Sul   |39,8   |
|Mato Grosso do Sul  |6,9    |
|Mato Grosso         |3,4    |
|Goiás               |17,7   |
|Distrito Federal    |444,1  |
|**Brasil (Média das razões)** |68,1|
|**Brasil (Razão das médias)** |22,4|
Fonte: IBGE, Censo Demográfico 2010.

## Outras funções de totais

*Totais* são parâmetros muito importantes, pois muitos outros parâmetros de interesse podem ser obtidos como funções de totais. Já vimos no capítulo \@ref(proporc) o exemplo das contagens de unidades pertencentes a determinados grupos que possuem características comuns, no caso em que as variáveis cujos totais se quer estimar são indicadoras da pertinência a tais grupos. No capítulo \@ref(visger) também verificamos que as médias populacionais são razões de totais, onde no denominador aparece o número $N$ de unidades na população, e no numerador vai o total da variável cuja média se quer definir. 

Neste capítulo já definimos as *razões de totais* populacionais, e agora vamos apresentar mais alguns parâmetros que podem ser definidos como funções de totais populacionais. Para introduzir o caso mais geral, considere um parâmetro $\theta$ que pode ser definido como uma função de $K$ totais populacionais, isto é:

\begin{equation} 
 \theta = f(Y_1, Y_2, ..., Y_K) 
\end{equation}

onde $Y_k$ é o total populacional da variável de pesquisa $y_k$, para $k=1,...,K$, e $f$ é uma função real que especifica como obter o valor de $\theta$ a partir dos totais das variáveis de pesquisa.

Um caso geral de interesse é o das funções lineares de totais populacionais, dadas por:

\begin{equation}
 \theta = f(Y_1, Y_2, ..., Y_K) = \sum_{k=1}^K a_k \, Y_k
\end{equation}

onde $a_k$ são constantes conhecidas, para $k=1,...,K$.

Um exemplo simples de função linear é a *diferença* entre dois totais populacionais especificados, dada por:

\begin{equation}
 D = \sum_{i\in U} y_{2i} - \sum_{i\in U} y_{1i} = Y_2 - Y_1
\end{equation}

Nesse caso, temos uma situação envolvendo $K=2$ totais populacionais, com $a_1 = 1$ e $a_2 = -1$. 

Outro exemplo de parâmetro que pode ser escrito como função de totais é o caso da *função de distribuição cumulativa* num ponto, dada por:

\begin{equation}
 F_y(a) = \displaystyle \frac{1}{N} \sum_{i\in U} I(y_i \le a) \quad
\end{equation}

Nesse caso, a situação envolve apenas dois totais populacionais ($K=2$), sendo a primeira definida como $y_{1i} \equiv I(y_i \le a)$ e a segunda $y_{2i} \equiv 1$, e a função definida como $f(Y_1, Y_2) = Y_1 / Y_2$.

A *variância* de uma variável de pesquisa $y$, dada por

\begin{equation}
 S^2_y = \frac{1}{N-1} \left[ \sum_{i\in U} {y_i}^2 - N \overline{Y}^2 \right] = \frac{1}{N-1} \left[ \sum_{i\in U} {y_i}^2 -  {Y}^2/N \right]
\end{equation}

também pode ser vista como uma função envolvendo três totais populacionais ($K=3$), sendo o primeiro definido como total da variável $y_{1i} \equiv y_i^2$, a segunda $y_{2i} \equiv y_i$, e a terceira como $y_{3i} \equiv 1$. A função que retorna a variância $S^2_y$ é definida como 
$f(Y_1, Y_2, Y_3) = \frac {1} {Y_3 - 1} \left[ Y_1 - (Y_2^2/Y_3) \right]$.

De maneira similar, a *covariância* e a *correlação* das variáveis $y$ e $z$ podem ser definidas como:

\begin{equation}
S_{y_1 , y_2} = \displaystyle \frac{1}{N-1} \sum_{i\in U} \left({y_{1i} - \overline{Y_1}} \right)  \left({y_{2i} - \overline{Y_2}} \right) = \frac{1}{N-1} \left[ \sum_{i\in U} {y_{1i}} {y_{2i}} - \, Y_1 Y_2 / {N} \right] \quad  
\end{equation}

e

\begin{equation}
{\rho}_{y_1 , y_2} = \frac{S_{y_1 , y_2}} {S_{y_1} S_{y_2}},
\end{equation}

onde a covariância pode ser vista como uma função envolvendo quatro totais populacionais ($K=4$), sendo o primeiro definido como o total $Y_1$ da variável $y_1$, o segundo o total $Y_2$ da variável $y_2$, o terceiro o total da variável definida como $y_{3i} \equiv y_{1i} y_{2i}$ e o quarto o total da variável definida como $y_{4i} \equiv 1$. Por simplicidade, a função que define a correlação foi definida em função da covariância e dos desvios-padrão das duas variáveis de interesse, mas também poderia ser escrita como função de totais como já ilustrado nos demais casos.

O ponto importante a destacar nesta seção é o fato de que muitos parâmetros de interesse podem ser vistos como funções de totais populacionais, e com isso, podem também ser estimados aplicando as funções que definem o parâmetro a estimadores dos totais correspondentes. Isto corresponde essencialmente a uma espécie de método dos momentos para estimar parâmetros populacionais, onde cada total populacional desconhecido é substituído na expressão do parâmetro por um estimador não viciado amostral do total correspondente.

Essa ideia pode ser aplicada de maneira bastante geral para obter estimadores para grande quantidade de parâmetros populacionais que possam ser escritos em função de totais populacionais de variáveis bem definidas. Para fixar as ideias, este método é aplicado primeiramente para obter estimador para uma *razão de totais*. 

## Estimando razões (de totais)

Para estimar razões de totais (ou médias) como $R$, o estimador “natural” é a *razão dos estimadores Horwitz-Thompson de total*:

\begin{equation}
\widehat{R} = \frac{ \sum_{i\in s} w_i y_i} {\sum_{i\in s} w_i x_i} = \frac{ \widehat{Y}_{HT} } {\widehat{X}_{HT}} (\#eq:eqraz2)
\end{equation}

**Notas**

1. Tanto o numerador como o denominador do estimador $\widehat{R}$ da razão $R$ podem variar com a amostra selecionada, $s$.

2. Apesar de termos estimadores não viciados para os totais populacionais $\widehat{Y}_{HT}$ e $\widehat{X}_{HT}$, em geral,  $E(Z/W) \ne E(Z)E(W)$, e portanto $E(\widehat{R}) = E(\widehat{Y}_{HT}/ \widehat{X}_{HT}) \ne E(\widehat{Y}_{HT})/E(\widehat{X}_{HT})= {Y} / {X} = R$.

3. Logo $\widehat{R}$ é um estimador viciado de $R$.

4. O vício de $\widehat{R}$ é pequeno e chamado de “vício técnico”, para distingui-lo de outros vícios potencialmente causados por problemas tais como erros de cobertura, não resposta e outros. Para amostras grandes (isto é, com $n$ grande), este vício é geralmente desprezível do ponto de vista prático. Veja discussão na seção \@ref(vicioraz).

5. Sob AAS, este estimador simplifica para:

\begin{equation}
\widehat{R}_{AAS} = \frac{\sum_{i\in s} y_i} {\sum_{i\in s} x_i} = \frac{\overline{y}} {\overline{x}}. (\#eq:eqraz3)
\end{equation}


## Estimando outras funções de totais

Quando o parâmetro de interesse é uma função de totais populacionais $\theta = f(Y_1, Y_2, ..., Y_K)$, o método mais simples para estimar esse parâmetro é aplicar a mesma função a estimadores não viciados dos totais, isto é, usar o estimador:

\begin{equation}
 \widehat{\theta} = f(\widehat{Y_1}, \widehat{Y_2}, ..., \widehat{Y_K})
\end{equation}

onde $\widehat{Y_k}$ é o estimador HT do total populacional da variável de pesquisa $y_k$, para $k=1,...,K$.

Para o caso de *funções lineares*, o estimador resultante será dado por:

\begin{equation}
 \widehat{\theta} = \sum_{k=1}^K a_k \, \widehat{Y_k}
\end{equation}

e será um estimador não viciado do parâmetro $\theta$. 

Neste caso, a variância do estimador também é relativamente simples de obter, e dada por:

\begin{eqnarray}
V_p \left( \widehat{\theta} \right) & = & 
\sum_{k=1}^K \sum_{j = 1}^K a_k \, a_j Cov_p \left( \widehat{Y_k} ,  \widehat{Y_j} \right) \\
 &=& \sum_{k=1}^K a_k \, V_p \left( \widehat{Y_k} \right) +  \sum_{k=1}^K \sum_{j \ne k = 1}^K a_k \, a_j Cov_p \left( \widehat{Y_k} ,  \widehat{Y_j} \right)
\end{eqnarray}

e um estimador dessa variância pode ser facilmente construído usando

\begin{eqnarray}
\widehat{V}_p \left( \widehat{\theta} \right) & = & \sum_{k=1}^K \sum_{j = 1}^K a_k \, a_j \widehat{Cov}_p \left( \widehat{Y_k} ,  \widehat{Y_j} \right) \\
& = & \sum_{k=1}^K a_k \, \widehat{V}_p \left( \widehat{Y_k} \right) +  \sum_{k=1}^K \sum_{j \ne k = 1}^K a_k \, a_j \widehat{Cov}_p \left( \widehat{Y_k} ,  \widehat{Y_j} \right)
\end{eqnarray}

Um resultado bastante útil é mostrado a seguir. Quando $\theta = \sum_{k=1}^K a_k \, Y_k$, então sua variância pode ser escrita como:

\begin{eqnarray}
V_p \left( \widehat{\theta} \right) & = & E_p \left( \widehat{\theta} -\theta \right)^2 \\ 
& = & E_p \left[ \sum_{k=1}^K a_k \left( \widehat{Y_k} - Y_k \right) \right]^2 \\
& = & E_p \left[ \sum_{k=1}^K a_k \sum_{i \in s} \pi_i^{-1} y_{ki} - \sum_{k=1}^K a_k \sum_{i \in U} y_{ki} \right]^2 \\
& = & E_p \left[ \sum_{i \in s} \pi_i^{-1} \left( \sum_{k=1}^K a_k y_{ki} \right) - \sum_{i \in U} \left( \sum_{k=1}^K a_k y_{ki} \right) \right]^2 \\
& = & E_p \left[ \sum_{i \in s} \pi_i^{-1} z_i - \sum_{i \in U} z_i \right]^2 \\
& = & E_p \left[ \widehat{Z}_{HT} - Z \right]^2 \\
& = & V_p \left( \widehat{Z}_{HT} \right)
\end{eqnarray}

onde $z_i = \sum _{k=1} ^K a_k y_{ki}$.

Verifica-se assim que a variância do estimador para $\theta$ pode ser obtida como a variância de um estimador de total para uma variável derivada $z$ definida de maneira apropriada, tornando assim a obtenção da variância do estimador do parâmetro uma tarefa mais simples, já que a variância de estimadores de total foi apresentada no capítulo \@ref(visger). Isso leva também à obtenção de estimadores da variância de forma simples, usando a mesma variável derivada:

\begin{equation}
\widehat{V}_p \left( \widehat{\theta} \right) = \widehat V_1(\widehat{Z}_{HT}) = \displaystyle \sum_{i \in s} \sum_{j \in s} \left( {d_i d_j} - {d_{ij}} \right) {z_i} {z_j}
\end{equation}

Este resultado tem utilidade também quando $\theta$ é uma função não linear de totais, mas essa função é contínua e diferenciável. Neste caso, é possível usar a técnica de *linearização de Taylor* para obter a variância aproximada do estimador e também um estimador para essa variância. A ideia dessa técnica é simples: aproximar o estimador não linear por uma quantidade linearizada, obtida a partir da expansão em Série de Taylor do estimador $\widehat{\theta}$ ao redor do ponto $\theta$. A expansão é dada por:

\begin{eqnarray}
 \widehat{\theta} & = & f(\widehat{Y}_1, \widehat{Y}_2, ..., \widehat{Y}_K) \\
 & = & f(Y_1, Y_2, ..., Y_K) + \sum_{k=1}^K \left[ \frac {\partial {f(Y_1, Y_2, ..., Y_K)}}   {\partial{Y_k}} \right] \left( \widehat{Y}_k - Y_k \right) + \\
 & \, & \sum_{q=2}^\inf \frac {1} {q!} \sum_{k=1}^K \left[ \frac {\partial ^q {f(Y_1, Y_2, ..., Y_K)}} {\partial  {Y_k}}^q \right] \left( \widehat{Y}_k - Y_k \right)^q \\
 & \doteq & f(Y_1, Y_2, ..., Y_K) + \sum_{k=1}^K \left[ \frac {\partial {f(Y_1, Y_2, ..., Y_K)}}   {\partial{Y_k}} \right] \left( \widehat{Y}_k - Y_k \right)
\end{eqnarray}

onde a aproximação da última linha advém da exclusão de todos os termos de ordem igual ou superior a 2.

É comum chamar de $\widehat{\theta}_L$ a quantidade

\begin{eqnarray}
 \widehat{\theta}_L & = & f(Y_1, Y_2, ..., Y_K) + \sum_{k=1}^K \left[ \frac {\partial {f(Y_1, Y_2, ..., Y_K)}} {\partial{Y_k}} \right] \left( \widehat{Y}_k - Y_k \right) \\
 & = & f(Y_1, Y_2, ..., Y_K) + \sum_{k=1}^K a_k \left( \widehat{Y}_k - Y_k \right) 
\end{eqnarray}

onde agora $a_k = \displaystyle\frac {\partial {f(Y_1, Y_2, ..., Y_K)}} {\partial{Y_k}}$, $k=1, 2, ..., K$.

Assim sendo, a obtenção da variância aproximada para o estimador não linear $\widehat{\theta}$ é feita calculando-se a variância do *estimador linearizado* $\widehat{\theta}_L$, que é dada por:

\begin{equation}
\widehat{V}_p \left( \widehat{\theta} \right) \doteq \widehat{V}_p \left( \widehat{\theta}_L \right) = \widehat V_1(\widehat{Z}_{HT}) = \displaystyle \sum_{i \in s} \sum_{j \in s} \left( {d_i d_j} - {d_{ij}} \right) {z_i} {z_j}
\end{equation}

onde $z_i =\displaystyle\sum_{k=1}^K \frac{\partial {f(Y_1, Y_2, ..., Y_K)}} {\partial{Y_k}} \, y_{ki}$.

## Analisando o vício do estimador da razão sob AAS {#vicioraz}

Sejam $\Delta y=\overline{y} - \overline{Y}$, e  $\Delta x=\overline{x} - \overline{X}$ os erros das estimativas de médias populacionais para as variáveis $x$ e $y$. 

Lembrando que $DP_{AAS}(\overline{y})=\sqrt{(1-f)}S_y/\sqrt{n}$, segue-se que $\Delta y$ e $\Delta x$  são de ordem $n^{-1/2}$ (a ordem de grandeza do desvio padrão). 

Portanto, 

$\displaystyle\frac{\overline{y}}{\overline{x}}=\frac{\overline{Y}+\Delta{y}}{\overline{x}+\Delta{x}}=\frac{\overline{Y}}{\overline{X}}\left(1+\frac{\Delta{y}}{Y}\right)\left(1+\frac{\Delta{x}}{X}\right)^{-1}$

Desenvolvendo-se o fator $\left(1+\frac{\Delta{x}}{X}\right)^{-1}$ como série de potências de $\Delta{x}$, tem-se: 

\begin{eqnarray}
\displaystyle\frac{\overline{y}}{\overline{x}}&=&\frac{\overline{Y}}{\overline{X}}\left(1+\frac{\Delta{y}}{Y}\right)\left(1+\frac{\Delta{x}}{X}\right)^{-1}\\ & = &\frac{\overline{Y}}{\overline{X}}\left(1+\frac{\Delta{y}}{Y}\right)\left[1-\frac{\Delta{x}}{X}+\left(\frac{\Delta{x}}{X}\right)^2+´´´\right]\\& = &\frac{\overline{Y}}{\overline{X}}\left(1+\frac{\Delta{y}}{Y}-\frac{\Delta{x}}{X}+\textrm{termos em} \,\Delta^2\right)
\end{eqnarray}

Logo:

$E(\widehat{R})=E(\overline{y}/\overline{x})=R\left[1+\displaystyle\frac{E(\Delta{y})}{\overline{Y}}-\frac{E(\Delta{x})}{\overline{X}}+\textrm{termos em}\,\, E(\Delta^2)\right]= R +\textrm{termos em ordem}\,\,n^{-1}$

porque $E(\Delta{y})=E(\Delta{x})=0$.

Assim, o vício é de ordem $n^{-1}$ e fica menor à medida que o tamanho da amostra cresce, daí o nome de *vício técnico*.

Vícios desse tipo são geralmente desprezados na prática, a menos que se tenha amostras *muito pequenas*.

## Erro Quadrático Médio (EQM) de $\widehat{R}$ sob AAS

Como $\widehat{R}$ tem um pequeno vício técnico, avaliamos seu *Erro Quadrático Médio (EQM)* sob AAS, ao invés da variância:

\begin{eqnarray}
EQM_{AAS}(\widehat{R}) & = & E_{AAS}\left(\widehat{R}-R\right)^2 \\ &=& E_{AAS}\left[R^2\left(\frac{\Delta{y}}{\overline{Y}}-\frac{\Delta{x}}{\overline{X}}\right)^2\right]+\textrm{termos em} \,\Delta^3 \\ &\doteq & R^2 E_{AAS}\left(\frac{\overline{y}-\overline{Y}}{\overline{Y}}-\frac{\overline{x}-\overline{X}}{\overline{X}}\right)^2 \\ &=& \frac{R^2}{\overline{Y}^2}E_{AAS}(\overline{y}-R\overline{x})^2\\ &=& \frac{(1-f)}{n\overline{X}^2}\frac{1}{(N-1)}\displaystyle\sum_{i\in U}\left(y_i-Rx_i\right)^2(\#eq:eqraz4)
\end{eqnarray}


Um estimador desse EQM que tem vício de ordem $n^{-1}$ é: 

\begin{equation}
\widehat{V}_{AAS}(\widehat{R})=\frac{(1-f)}{n\overline{x}^2}\frac{1}{(n-1)}\displaystyle\sum_{i\in s}\left(y_i-\widehat{R}x_i\right)^2 (\#eq:eqraz5)
\end{equation}
Veja [@Cochran1977].

Portanto, sob AAS temos a seguinte estrutura para estimação de razões:

(1)	$\widehat{R}$ estima $R$ e $E_{AAS}(\widehat{R})=R+O(n^{-1})$;

(2)	$EQM_{AAS}(\widehat{R})=\displaystyle\frac{(1-f)}{n\overline{X}^2}\frac{\displaystyle\sum_{i\in U}\left(y_i-Rx_i\right)^2}{N-1}+ O\left(n^{-3/2}\right)$ 

(3) $\widehat{V}_{AAS}(\widehat{R})=\displaystyle\frac{(1-f)}{n\overline{x}^2}\frac{1}{(n-1)}\displaystyle\sum_{i\in s}\left(y_i-\widehat{R}x_i\right)^2$

(4)	$\displaystyle\frac{\widehat{R}-R}{{\sqrt{\widehat{V}_{AAS}(\widehat{R})}}}\approx N(0;1)$  para $n$ grande.

**(#exm:exmrazao2)** Estimando Razões e Médias de Razões

Considere a população de municípios brasileiros fornecida no arquivo MunicBR.xlsx.

1.	Selecione uma AAS de $n=20$ municípios, e use esta amostra para estimar os seguintes parâmetros populacionais:

    a. Densidade habitacional média por $km^2$ no Brasil;

    b. Média da densidade habitacional por $km^2$ por município.

2.	Para cada uma das estimativas acima:

    a.	Estime o erro padrão e o coeficiente de variação; 

    b.	Compare com os correspondentes parâmetros populacionais.
    
 INCLUIR o conteúdo do arquivo Exercícios Unidade 05.R




## Exercícios

**(#exr:exerazao1)** Identifique e defina duas razões que você já tenha utilizado em seu trabalho.

